### ISSUE TITLE
GSOC?

### ISSUE THREAD

**Issue by minad** [text-utf8/META#4]
Would this project make sense in the context of the GSOC? See https://www.reddit.com/r/haskell/comments/ae1i6z/reminder_please_submit_gsoc_ideas/edmpgit

I think text-utf8 originated from a GSOC?

**Comment by hvr** [comment]
Yeah, I think this would be a good fit for a GSOC assuming the scope for the base-goal is defined appropriately so it's neither too easy nor too much work. What we need is executing a couple of experiments (we have about 3-4 refactorings we'd like to see tried out and benchmarked) as well as figuring out how to deal with the `text-icu` issue in a reasonably performant way. Above this baseline there'd be a couple of stretch-goals if it's not already enough to fill a GSOC :-)

**Comment by jaspervdj** [comment]
@hvr Would you be able to write this up a little for a GSoC proposal?  I wouldn't mind back-up mentoring this since I was somewhat involved in this fork near the start :-)
